version: '3.9'

services:
   mysqldb:
    container_name: mysqldb
    image: 'mysql:latest'
    ports:
      - "3307:3306"
    environment:
           MYSQL_DATABASE: helpdesk
           MYSQL_ROOT_PASSWORD: HelpD3sk
           MYSQL_PASSWORD: HelpD3sk
    volumes:
           - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
           - ./my-datavolume:/var/lib/mysql
   backendserver:
    restart: always
    container_name: springapp
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/helpdesk?useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "HelpD3sk"
    depends_on:
      - mysqldb



   frontend:
    build: ./frontend
    ports:
           - "4200:4200"
    volumes:
       - ./frontend:/usr/src/app/frontend
       - /usr/src/app/frontend/node_modules      