version: '3.9'

services:

  db:
    image: 'mysql/mysql-server:5.7'
    ports:
           - "3306:3306"
    environment:
           - MYSQL_ROOT_PASSWORD=HelpD3sk
           - MYSQL_DATABASE=HelpDesk
           - MYSQL_USER=root
           - MYSQL_ROOT_HOST=%
    volumes:
           - ./my-datavolume:/var/lib/mysql
    healthcheck:
           test: ["CMD","mysqladmin","ping","-h","localhost"]
           timeout: 20s
           retries: 10
    restart: always
  
  backendserver:
    build: ./backend
    ports:
           - "8080:8080"
    links:
           - "db"
    depends_on:
           - "db"
    restart: always

  frontend:
    build: ./frontend
    links:
           - "backendserver"
    depends_on:
           - "backendserver"
    ports:
           - "4200:80"      